### ISSUE TITLE
./run-wordcount.sh 脚本运行

### ISSUE THREAD

**Issue by GuaiLong618** [kiwenlau/hadoop-cluster-docker#65]
root@hadoop-master:~# ./run-wordcount.sh 
18/12/04 03:48:57 INFO client.RMProxy: Connecting to ResourceManager at hadoop-master/172.18.0.2:8032
18/12/04 03:48:58 INFO input.FileInputFormat: Total input paths to process : 2
18/12/04 03:48:58 INFO mapreduce.JobSubmitter: number of splits:2
18/12/04 03:48:58 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1543895269322_0001
18/12/04 03:48:59 INFO impl.YarnClientImpl: Submitted application application_1543895269322_0001
18/12/04 03:48:59 INFO mapreduce.Job: The url to track the job: http://hadoop-master:8088/proxy/application_1543895269322_0001/
18/12/04 03:48:59 INFO mapreduce.Job: Running job: job_1543895269322_0001
18/12/04 03:49:10 INFO mapreduce.Job: Job job_1543895269322_0001 running in uber mode : false
18/12/04 03:49:10 INFO mapreduce.Job:  map 0% reduce 0%
18/12/04 03:49:20 INFO mapreduce.Job: Task Id : attempt_1543895269322_0001_m_000001_0, Status : FAILED
Exception from container-launch.
Container id: container_1543895269322_0001_01_000003
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
	at org.apache.hadoop.util.Shell.run(Shell.java:456)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

我看了issue,但没有解决这个问题.

**Comment by Koenma413** [comment]
> root@hadoop-master:~# ./run-wordcount.sh
> 18/12/04 03:48:57 INFO client.RMProxy: Connecting to ResourceManager at hadoop-master/172.18.0.2:8032
> 18/12/04 03:48:58 INFO input.FileInputFormat: Total input paths to process : 2
> 18/12/04 03:48:58 INFO mapreduce.JobSubmitter: number of splits:2
> 18/12/04 03:48:58 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1543895269322_0001
> 18/12/04 03:48:59 INFO impl.YarnClientImpl: Submitted application application_1543895269322_0001
> 18/12/04 03:48:59 INFO mapreduce.Job: The url to track the job: http://hadoop-master:8088/proxy/application_1543895269322_0001/
> 18/12/04 03:48:59 INFO mapreduce.Job: Running job: job_1543895269322_0001
> 18/12/04 03:49:10 INFO mapreduce.Job: Job job_1543895269322_0001 running in uber mode : false
> 18/12/04 03:49:10 INFO mapreduce.Job: map 0% reduce 0%
> 18/12/04 03:49:20 INFO mapreduce.Job: Task Id : attempt_1543895269322_0001_m_000001_0, Status : FAILED
> Exception from container-launch.
> Container id: container_1543895269322_0001_01_000003
> Exit code: 1
> Stack trace: ExitCodeException exitCode=1:
> at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
> at org.apache.hadoop.util.Shell.run(Shell.java:456)
> at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
> at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
> at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
> at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
> at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at java.lang.Thread.run(Thread.java:745)
> 
> 我看了issue,但没有解决这个问题.
我已经解决了这个问题, 我虚拟机设置1G的内存,内存不足.
我修改为4G内存,运行正常.

**Comment by GuaiLong618** [comment]
我已经解决了这个问题, 我虚拟机设置1G的内存,内存不足.
我修改为4G内存,运行正常.

**Comment by leonlee723** [comment]
@Koenma413 我把start-container.sh的docker run 加上了-m 4096M，还是有这个问题，请问你是怎么改的，非常感谢

**Comment by lonngxiang** [comment]
Retrying connect to server: hadoop-master/172.20.0.2
:8032.   我遇到这个问题
